##### username

  ```sql
  
  ```














###### BigUsername:
```sql
root:calvin
administrator:password
NetLinx:password
administrator:Amx1234!
amx:password
amx:Amx1234!
admin:1988
admin:admin
Administrator:Vision2
cisco:cisco
root:fidel123
user:user
root:default
localadmin:localadmin
Root:wago
Admin:wago
User:user
Guest:guest
root:rootpasswd
admin:password
adtec:none
root:timeserver
root:password
Admin:Su
root:admin
admin:motorola
Admin:5001
User:1001
GE:GE
Admin:Pass
device:apc
apc:apc
root:anni2013
root:xc3511
root:dreambox
root:vizxv
admin:1111111
admin:smcadmin
admin:4321
888888:888888
666666:666666
ubnt:ubnt
admin:22222
adminttd:adminttd
root:!root
admin:epicrouter
tech:tech
manager:manager
smc:smcadmin
netscreen:netscreen
netopia:netopia
root:888888
root:xmhdipc
root:juantech
root:123456
root:54321
support:support
root:root
root:12345
root:pass
admin:admin1234
root:1111
admin:1111
root:666666
root:1234
root:klv123
Administrator:admin
service:service
guest:guest
guest:12345
admin1:password
administrator:1234
root:klv1234
root:Zte521
root:hi3518
root:jvbzd
root:anko
root:zlxx.
root:7ujMko0vizxv
root:7ujMko0admin
root:system
root:ikwb
root:dreambox
root:user
root:realtek
root:00000000
admin:1234
admin:12345
default:OxhlwSG8
admin:tlJwpbo6
default:S2fGqNFs
admin:meinsm
supervisor:supervisor
admin:123456
root:zlxx
dm:telnet
webguest:1
Liebert:Liebert
User:User
admin:avocent
root:linux
admin:system
user:public
admin:private
guest:guest
admin:admin
root:root
qbf77101:hexakisoctahedron
ftpuser:password
USER:USER
Basisk:Basisk
sconsole:12345
root:5up
root:cat1029
MayGion:maygion.com
admin:cat1029
admin:ZmqVfoSIP
default:antslq
admin:microbusiness
admin:jvc
root:GM8182
root:uClinux
Alphanetworks:wrgg19_c_dlwbr_dir300
Alphanetworks:wrgn49_dlob_dir600b
Alphanetworks:wrgn23_dlwbr_dir600b
Alphanetworks:wrgn22_dlwbr_dir615
Alphanetworks:wrgnd08_dlob_dir815
Alphanetworks:wrgg15_di524
Alphanetworks:wrgn39_dlob.hans_dir645
Alphanetworks:wapnd03cm_dkbs_dap2555
Alphanetworks:wapnd04cm_dkbs_dap3525
Alphanetworks:wapnd15_dlob_dap1522b
Alphanetworks:wrgac01_dlob.hans_dir865
Alphanetworks:wrgn23_dlwbr_dir300b
Alphanetworks:wrgn28_dlob_dir412
Alphanetworks:wrgn39_dlob.hans_dir645_V1
root:oelinux123
mg3500:merlin
root:cxlinux
root:1001chin
root:china123
admin:symbol
admin:Symbol
admin:superuser
admin:admin123
root:20080826
suma123:panger123
debug:debug124
root:root126
guest:
root:AK2040jk
anonymous:anonymous
root:rootpasswd
root:12hrs37
ftp:b1uRR3
admin:admin
localadmin:localadmin
admin:1234
apc:apc
admin:nas
Root:wago
Admin:wago
User:user
Guest:guest
ftp:ftp
admin:password
a:avery
admin:123456
adtec:none
admin:admin12345
none:dpstelecom
instrument:instrument
user:password
root:password
default:default
admin:default
nmt:1234
admin:Janitza
supervisor:supervisor
user1:pass1
avery:avery
IEIeMerge:eMerge
ADMIN:12345
beijer:beijer
Admin:admin
admin:1234
admin:1111
root:admin
se:1234
admin:stingray
device:apc
apc:apc
dm:ftp
dmftp:ftp
httpadmin:fhttpadmin
user:system
MELSEC:MELSEC
QNUDECPU:QNUDECPU
ftp_boot:ftp_boot
uploader:ZYPCOM
ftpuser:password
USER:USER
qbf77101:hexakisoctahedron
ntpupdate:ntpupdate
sysdiag:factorycast@schneider
wsupgrade:wsupgrade
pcfactory:pcfactory
loader:fwdownload
test:testingpw
webserver:webpages
fdrusers:sresurdf
nic2212:poiuypoiuy
user:user00
su:ko2003wa
MayGion:maygion.com
admin:9999
PlcmSpIp:PlcmSpIp
root:mysql
root:root
root:chippc
admin:admin
root:
root:nagiosxi
root:usbw
cloudera:cloudera
root:cloudera
root:moves
moves:moves
root:testpw
root:p@ck3tf3nc3
mcUser:medocheck123
root:mktt
root:123
dbuser:123
asteriskuser:amp109
asteriskuser:eLaStIx.asteriskuser.2oo7
root:raspberry
root:openauditrootuserpassword
root:vagrant
root:123qweASD#
dcmadmin:passw0rd
postgres:amber
postgres:postgres
postgres:password
postgres:admin
admin:admin
admin:password
postgres:123
admin:admin
root:root
root:admin
admin:root
root:Admin
admin:Admin
Alphanetworks:wrgn49_dlob_dir300b5
admin
root
!root
11111:x-admin
1234:1234
abc:cascade
adm
admin:_Cisco
admin:0
admin:123
admin:1234
Admin:123456
admin:1234admin
admin:2222
admin:3477
admin:3ascotel
admin:9999
admin:access
admin:adminttd
admin:adslolitec
admin:adslroot
admin:adtran
admin:asante
admin:ascend
admin:atc123
admin:atlantis
admin:backdoor
admin:barricade
admin:bintec
admin:BRIDGE
admin:comcomcom
admin:default
admin:enter
admin:epicrouter
admin:extendnet
admin:hello
admin:help
admin:Intel
admin:ironport
admin:isee
admin:letmein
admin:leviton
admin:michelangelo
admin:microbusiness
admin:mu
admin:my_DEMARC
admin:netadmin
admin:NetCache
admin:NetICs
admin:noway
admin:OCS
admin:P@55w0rd!
admin:PASSWORD
admin:passwort
admin:pento
admin:pfsense
admin:private
admin:public
admin:rmnetlm
admin:setup
admin:sitecom
admin:smcadmin
admin:SMDR
admin:speedxess
admin:SUPER
admin:switch
admin:Symbol
admin:sysAdmin
admin:system
admin:TANDBERG
admin2:changeme
Administrator
Administrator:admin
ADMINISTRATOR:ADMINISTRATOR
Administrator:changeme
Administrator:ganteng
Administrator:ggdaseuaimhrke
Administrator:password
Administrator:smcadmin
adminstat:OCS
adminstrator:changeme
adminttd:adminttd
adminuser:OCS
adminview:OCS
ADMN:admn
ADSL:expert03
ADVMAIL:HP
ADVMAIL:HPOFFICE DATA
Alphanetworks:wrgg15_di524
ami
Any:12345
apc:apc
bbsd-client:changeme2
bbsd-client:NULL
cablecom:router
ccrusr:ccrusr
cellit:cellit
cisco
cisco:cisco
CISCO15:otbu+1
citel:citel
corecess:corecess
craft
CSG:SESAME
cusadmin:highspeed
dadmin:dadmin01
davox:davox
debug:d.e.b.u.g
debug:synnet
deskalt:password
deskman:changeme
desknorm:password
deskres:password
diag:danger
diag:switch
disttech:4tas
D-Link:D-Link
draytek:1234
echo:User
Factory:56789
FIELD:HPONLY
FIELD:HPP187 SYS
FIELD:HPWORD PUB
FIELD:LOTUS
FIELD:MANAGER
FIELD:MGR
FIELD:SERVICE
FIELD:SUPPORT
GEN1:gen1
GEN2:gen2
guest
guest:guest
guest:User
HELLO:FIELD.SUPPORT
HELLO:MANAGER.SYS
HELLO:MGR.SYS
HELLO:OP.OPERATOR
helpdesk:OCS
hsa:hsadb
HTTP:HTTP
iclock:timely
images:images
install:secret
installer:installer
intermec:intermec
IntraStack:Asante
IntraSwitch:Asante
l2:l2
l3:l3
login:admin
login:password
m1122:m1122
MAIL:HPOFFICE
MAIL:MAIL
MAIL:MPE
MAIL:REMOTE
MAIL:TELESUP
maint:maint
maint:ntacdmax
manage !manage
Manager
Manager:Admin
MANAGER:COGNOS
manager:friend
MANAGER:HPOFFICE
MANAGER:ITF3000
manager:manager
MANAGER:SECURITY
MANAGER:SYS
MANAGER:TCH
MANAGER:TELESUP
manuf:xxyyzz
MD110:help
mediator:mediator
MGR:CAROLIAN
MGR:CCC
MGR:CNAS
MGR:COGNOS
MGR:CONV
MGR:HPDESK
MGR:HPOFFICE
MGR:HPONLY
MGR:HPP187
MGR:HPP189
MGR:HPP196
MGR:INTX3
MGR:ITF3000
MGR:NETBASE
MGR:REGO
MGR:RJE
MGR:ROBELLE
MGR:SECURITY
MGR:SYS
MGR:TELESUP
MGR:VESOFT
MGR:WORD
MGR:XLSERVER
MICRO:RSX
mlusr:mlusr
monitor:monitor
NAU:NAU
netopia:netopia
netrangr:attack
netscreen:netscreen
NICONEX:NICONEX
nokai:nokai
nokia:nokia
operator
operator:1234
OPERATOR:COGNOS
OPERATOR:DISC
operator:operator
OPERATOR:SUPPORT
OPERATOR:SYS
OPERATOR:SYSTEM
patrol:patrol
PCUSER:SYS
PRODDTA:PRODDTA
public
radware:radware
readonly:lucenttech2
readwrite:lucenttech1
recovery:recovery
replicator:replicator
RMUser1:password
ro:ro
root:1234
root:12345
root:3ep5w2u
root:admin_1
root:ascend
root:attack
root:blender
root:davox
root:default
root:fivranne
root:ggdaseuaimhrke
root:iDirect
root:Mau'dib
root:pass
root:password
root:tini
root:tslinux
RSBCMON:SYS
rw:rw
rwa:rwa
scmadmin:scmchangeme
scout:scout
secret:secret
secure:secure
security:security
Service:5678
service:smile
setup:changeme
setup:setup
smc:smcadmin
SPOOLMAN:HPOFFICE
SSA:SSA
storwatch:specialist
stratacom:stratauser
super:super
super:surt
super.super
super.super:master
superman:talent
superuser
superuser:123456
superuser:admin
supervisor:supervisor
support:support
sysadm:Admin
sysadm:anicust
SYSADM:sysadm
sysadmin:PASS
sysadmin:password
SYSDBA:masterkey
target:password
teacher:password
tech
tech:tech
telecom:telecom
tellabs:tellabs#1
temp1:password
tiger:tiger123
TMAR#HWMT8007079
topicalt:password
topicnorm:password
topicres:password
User
user:password
vcr:NetVCR
vt100:public
wlse:wlsedb
WP:HPOFFICE
write:private
xd:xd
root:mysql
root:root
root:chippc
admin:admin
root:
root:nagiosxi
root:usbw
cloudera:cloudera
root:cloudera
root:moves
moves:moves
root:testpw
root:p@ck3tf3nc3
mcUser:medocheck123
root:mktt
root:123
dbuser:123
asteriskuser:amp109
asteriskuser:eLaStIx.asteriskuser.2oo7
root:raspberry
root:openauditrootuserpassword
root:vagrant
root:123qweASD#
```
